language: ruby
rvm:
- 2.2.0
- 2.1.1
- 2.0.0
- jruby-head
- ruby-head
- rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
deploy:
  provider: rubygems
  api_key:
    secure: Dd0l16iSFErUc9ClkPfStyqMKFY1PpA1qX5+59kTwF6+3srgNiDLzlLnxxAj7ESNS5JCRSbt0URWIotRApNTz0qAdPww5radc+9y6iDtRU7OGh1N3aFJZDtYv+0gs0dzm5tQjrPBwePQOLnzN5x/3iHv9Ei1avk3cqQwoWPrhIg=
  gem: haecksler
  on:
    tags: true
    repo: falti/haecksler
